package com.cnstn.authuser.entity;

public enum WorkflowType {
    EVENT_WORKFLOW,
    ROOM_RESERVATION_WORKFLOW,
    EQUIPMENT_RESERVATION_WORKFLOW,
    EXTERNAL_PARTNER_WORKFLOW,
    INTERVENTION_WORKFLOW,
    GED_DOCUMENT_WORKFLOW
}
