package com.cnstn.authuser.entity;

public enum WorkflowStepCode {
    EVENT_DRAFT_REVIEW,
    EVENT_MANAGER_REVIEW,
    EVENT_SECURITY_REVIEW,
    EVENT_DSN_APPROVAL,
    EVENT_ROOM_PREPARATION,
    EVENT_PUBLICATION,
    EVENT_POST_EVENT_REPORT,
    EVENT_EXTERNAL_COMMUNICATION,
    EVENT_SOUTENANCE_CHECKPOINT,

    ROOM_REQUEST_REVIEW,
    ROOM_SECURITY_REVIEW,
    ROOM_CONFIRMATION,

    EQUIPMENT_REQUEST_REVIEW,
    EQUIPMENT_SECURITY_REVIEW,
    EQUIPMENT_CONFIRMATION,

    PARTNER_REQUEST_REVIEW,
    PARTNER_SECURITY_REVIEW,
    PARTNER_DSN_APPROVAL,

    INTERVENTION_REQUEST_REVIEW,
    INTERVENTION_ASSIGNMENT,
    INTERVENTION_CLOSURE,

    GED_DRAFT_REVIEW,
    GED_QUALITY_REVIEW,
    GED_PUBLICATION
}
