server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notification_db
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://host.docker.internal:8090/realms/cnstn-intranet}
app:
  auth-user-service:
    base-url: ${AUTH_USER_SERVICE_URL:http://auth-user-service:8081}
  mail:
    enabled: ${MAIL_ENABLED:true}
